spring.application.name=api-gateway
server.port=9000

services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082

# ==========================================================
# TODO GW-3 – Cấu hình Keycloak Issuer URI
# ----------------------------------------------------------
# YÊU CẦU:
#   Thêm property sau để Spring Security biết địa chỉ Keycloak
#   và tự động tải Public Key (JWKS) để xác minh chữ ký JWT.
#
#   spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
#
# LƯU Ý:
#   Keycloak phải đang chạy (docker compose up -d) trước khi
#   khởi động API Gateway.
# ==========================================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm

management.endpoints.web.exposure.include=health
